src/Entity/Lesson.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LessonRepository")
 */
class Lesson
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     *
     * @Serializer\Groups({"Default", "Getlesson", "Deserialization", "GetStudentPresences"})
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ClassGroup", inversedBy="lessons")
     * @ORM\JoinColumn(nullable=true, onDelete="SET NULL")
     * @Serializer\Type("EntityId<App\Entity\ClassGroup>")
     * @Serializer\Groups({"Default", "Deserialization"})
     * @Assert\NotBlank()
     */
    private $classGroup;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Teacher", inversedBy="lessons")
     * @ORM\JoinColumn(nullable=true, onDelete="SET NULL")
     * @Serializer\Type("EntityId<App\Entity\Teacher>")
     * @Serializer\Groups({"Default", "Deserialization"})
     * @Assert\NotBlank()
     */
    private $teacher;

    /**
     * @ORM\OneToMany(targetEntity="StudentPresence", mappedBy="lesson", orphanRemoval=true, cascade={"persist"})
     * @Serializer\Groups({"Default", "Deserialization"})
     * @Assert\Valid()
     */
    private $studentPresences;

    /**
     * @ORM\Column(type="datetime")
     * @var \DateTime
     * @Serializer\Groups({"Default", "Getlesson", "Deserialization", "GetStudentPresences"})
     * @Assert\DateTime()
     * @Assert\LessThan(propertyPath="dateEnd")
     */
    private $dateStart;

    /**
     * @ORM\Column(type="datetime")
     * @var \DateTime
     * @Serializer\Groups({"Default", "Getlesson", "Deserialization", "GetStudentPresences"})
     * @Assert\DateTime()
     * @Assert\GreaterThan(propertyPath="dateStart")
     */
    private $dateEnd;

    /**
     * @ORM\Column(type="string", length=50)
     * @Serializer\Groups({"Default", "Getlesson", "Deserialization", "GetClass"})
     */
    private $name;

    public function __construct()
    {
        $this->studentPresences = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @Serializer\VirtualProperty("getClassGroup")
     * @Serializer\Groups({"Getlesson"})
     * @Serializer\Type("App\Entity\ClassGroup")
     * @Serializer\MaxDepth(1)
     * @return ClassGroup|null
     */
    public function getClassGroup(): ?ClassGroup
    {
        return $this->classGroup;
    }

    public function setClassGroup(?ClassGroup $classGroup): self
    {
        $this->classGroup = $classGroup;

        return $this;
    }

    /**
     * @Serializer\VirtualProperty("getTeacher")
     * @Serializer\Groups({"Getlesson"})
     * @Serializer\Type("App\Entity\Teacher")
     * @Serializer\MaxDepth(1)
     * @return Teacher|null
     */
    public function getTeacher(): ?Teacher
    {
        return $this->teacher;
    }

    public function setTeacher(?Teacher $teacher): self
    {
        $this->teacher = $teacher;

        return $this;
    }

    /**
     * @Serializer\VirtualProperty("getStudentPresences")
     * @Serializer\Groups({"Getlesson"})
     * @Serializer\MaxDepth(2)
     * @return Collection|StudentPresence[]
     */
    public function getStudentPresences(): Collection
    {
        return $this->studentPresences;
    }

    public function addStudentPresence(StudentPresence $studentPresence): self
    {
        if (!$this->studentPresences->contains($studentPresence)) {
            $this->studentPresences[] = $studentPresence;
            $studentPresence->setlesson($this);
        }

        return $this;
    }

    public function removeStudentPresence(StudentPresence $studentPresence): self
    {
        if ($this->studentPresences->contains($studentPresence)) {
            $this->studentPresences->removeElement($studentPresence);
            // set the owning side to null (unless already changed)
            if ($studentPresence->getlesson() === $this) {
                $studentPresence->setlesson(null);
            }
        }

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->dateStart;
    }

    public function setDateStart(\DateTimeInterface $dateStart): self
    {
        $this->dateStart = $dateStart;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->dateEnd;
    }

    public function setDateEnd(\DateTimeInterface $dateEnd): self
    {
        $this->dateEnd = $dateEnd;

        return $this;
    }

    public function getDuration(): int
    {
        return $this->dateStart->diff($this->dateEnd)->h;
    }

    public function getName()
    {
        return $this->name;
    }

    public function setName($name): Lesson
    {
        $this->name = $name;

        return $this;
    }
}

src/Form/StudentType.php
<?php

namespace App\Form;

use App\Entity\ClassGroup;
use App\Entity\Student;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Routing\RouterInterface;
use Vich\UploaderBundle\Form\Type\VichImageType;

class StudentType extends AbstractType
{
    private $router;

    public function __construct(RouterInterface $router)
    {
        $this->router = $router;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username', TextType::class, [
                'label' => 'Numéro étudiant'
            ])
            ->add('firstname', TextType::class, [
                'label' => 'Prénom'
            ])
            ->add('lastname', TextType::class, [
                'label' => 'Nom'
            ])
            ->add('email', EmailType::class, [])
            ->add('classGroup', EntityType::class, [
                'label' => 'Classe',
                'class' => ClassGroup::class,
                'choice_label' => 'name',
                'attr' => ['class' => 'select2'],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Student::class,
            'userId' => null,
        ]);
    }
}

src/Controller/Admin/StudentController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Student;
use App\Form\StudentType;
use App\Repository\StudentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/student")
 */
class StudentController extends AbstractController
{
    /**
     * @Route("/", name="student_index", methods={"GET"})
     */
    public function index(StudentRepository $studentRepository): Response
    {
        return $this->render('admin/student/index.html.twig', [
            'students' => $studentRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="student_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $student = new Student();
        $form = $this->createForm(StudentType::class, $student);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $student->setPassword(random_bytes(10));
            $this->addFlash('info',$student->getPassword());
            $entityManager->persist($student);
            $entityManager->flush();

            return $this->redirectToRoute('student_index');
        }

        return $this->render('admin/student/new.html.twig', [
            'student' => $student,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="student_show", methods={"GET"})
     */
    public function show(Student $student): Response
    {
        return $this->render('admin/student/show.html.twig', [
            'student' => $student,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="student_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Student $student): Response
    {
        $form = $this->createForm(StudentType::class, $student);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('student_index', [
                'id' => $student->getId(),
            ]);
        }

        return $this->render('admin/student/edit.html.twig', [
            'student' => $student,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="student_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Student $student): Response
    {
        if ($this->isCsrfTokenValid('delete'.$student->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($student);
            $entityManager->flush();
        }

        return $this->redirectToRoute('student_index');
    }
}

src/Controller/Api/StudentController.php
<?php

namespace App\Controller\Api;

use App\Entity\Lesson;
use App\Entity\Student;
use App\Entity\StudentPresence;
use App\Entity\User;
use App\Form\StudentImageType;
use App\HttpFoundation\File\ApiUploadedFile;
use FOS\RestBundle\Controller\Annotations as Rest;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Vich\UploaderBundle\Handler\DownloadHandler;

/**
 * @Route("/student")
 */
class StudentController extends UserController
{
    /**
     * @Rest\Post("/update_password", name="student_update_password")
     * @IsGranted("ROLE_STUDENT")
     *
     * @param Request                      $request
     * @param UserPasswordEncoderInterface $passwordEncoder
     *
     * @return bool
     */
    public function updatePassword(Request $request, UserPasswordEncoderInterface $passwordEncoder)
    {
        return parent::updatePassword($request, $passwordEncoder);
    }

    /**
     * @Rest\Post("/reset_password", name="student_reset_password")
     * @IsGranted("ROLE_STUDENT")
     *
     * @param User $user
     *
     */
    public function resetPassword(User $user)
    {
        return parent::resetPassword($user);
    }

    /**
     * @Rest\Post("/photo", name="student_photo_set")
     * @IsGranted("ROLE_STUDENT")
     *
     * @param Request $request
     *
     * @return mixed
     */
    public function setPhoto(Request $request)
    {
        /** @var Student $student */
        $student = $this->getUser();

        $form = $this->createForm(StudentImageType::class, $student);

        $file = new ApiUploadedFile($request->request->get('photoBase64'), $request->request->get('extension'));

        $form->submit(['photoFile' => ['file' => $file]]);

        if (!$form->isSubmitted() || !$form->isValid()) {
            throw new HttpException(Response::HTTP_BAD_REQUEST, "Envoi de la photo impossible");
        }

        $this->getDoctrine()->getManager()->flush();

        if ($student->getPhoto() === null) {
            throw new NotFoundHttpException("La photo n'existe pas");
        }

        return $this->generateUrl('api_student_get_photo', ['id' => $student->getId()], RouterInterface::ABSOLUTE_URL);
    }

    /**
     * @Route("/{id}/photo", name="student_get_photo")
     */
    public function getPhoto(Student $student, DownloadHandler $downloadHandler) // TODO : Refacto with classic StudentController
    {
        // Only the student owning the file, the admins and the teachers who have the student in their class can access the photo
        if ($this->getUser() == $student || $this->isGranted('ROLE_ADMIN') || ($this->isGranted('ROLE_TEACHER') && $this->getUser()->teachToStudent($student))) {
            if ($student->getPhoto() === null) {
                throw $this->createNotFoundException('This student does not have a photo');
            }
            return $downloadHandler->downloadObject($student, 'photoFile', null, null, false);
        } else {
            throw $this->createAccessDeniedException('You do not have access to this photo.');
        }
    }

    /**
     * @Rest\Get("/{id}/attendances", name="get_attendances")
     * @param Request $request
     * @param int $id
     * @return JsonResponse
     */
    public function getStudentName(Request $request, int $id) {
        $em = $this->getDoctrine()->getManager();

        /** @var Student $student */
        $student = $em->getRepository(Student::class)->find($id);

        if ($student === null) {
            return new JsonResponse('Student not found', 404);
        }

        $response = [];
        $response['student']['id'] = $student->getId();
        $response['student']['username'] = $student->getUsername();
        $response['student']['firstname'] = $student->getFirstname();
        $response['student']['lastname'] = $student->getLastname();
        $response['student']['role'] = $student->getRoles();

        /** @var StudentPresence $presences */
        $presences = $student->getPresences();

        /** @var StudentPresence $presence */
        foreach ($presences as $presence) {
            if (!$presence->getPresent() || ($presence->getPresent() && !is_null($presence->getLate()))) {
                /** @var Lesson $lesson */
                $lesson = $presence->getLesson();
                $lessonName = $lesson->getName();
                $response['student'][$lessonName]['id'] = $lesson->getId();
                $response['student'][$lessonName]['schedule']['beginning'] = $lesson->getDateStart();
                $response['student'][$lessonName]['schedule']['ending'] = $lesson->getDateEnd();
                $response['student'][$lessonName]['attendance']['presence'] = $presence->getPresent();
                $response['student'][$lessonName]['attendance']['excuse']['description'] = $presence->getExcuseDescription();
                $response['student'][$lessonName]['attendance']['excuse']['proof'] = $presence->getExcuseProof();
                $response['student'][$lessonName]['attendance']['excuse']['isValidated'] = $presence->getExcuseValidated();
                $response['student'][$lessonName]['attendance']['delay'] = $presence->getLate();
            }
        }

        return new JsonResponse($response, 500);
    }

}

templates/student/absence.html.twig
<table class="table">
    <thead>
    <tr>
        <th>Date</th>
        <th>Nom de l'étudiant</th>
        <th>Absence/Retard</th>
        <th>Raison</th>
        <th>Justificatif</th>
    </tr>
    </thead>
    <tbody>
    {% for presence in presences %}
        {% if presence.present != true or presence.late != null %}
            {% set status = presence.excuseValidated is null
                ? '<span class=\"badge badge-primary\">En attente de validation</span>'
                : presence.excuseValidated == true
                ? '<span class=\"badge badge-success\">Validé</span>'
                : '<span class=\"badge badge-danger\">Refusé</span>' %}
            <tr>
                <td>{{ presence.lesson.dateStart|date("Y-m-d H:i:s") }}</td>
                <td>
                    <a href="{{ path('student_show', { 'id': presence.student.id }) }}">{{ presence.student.firstname ~ ' ' ~ presence.student.lastname }}</a>
                </td>
                <td>{{ presence.present ? 'Retard de ' ~ presence.late|date("Y-m-d H:i:s") ~ 'm' : 'Absence de ' ~ presence.lesson.duration ~ 'h' }}</td>
                <td>{{ presence.excuseValidated ? presence.excuseDescription : '<span class="badge badge-danger">Non justifié</span>' }}</td>
                <td>
                    {% if presence.excuseProof is not null %}
                        {{ status|raw }}<br>
                        <button class="btn btn-secondary mt-2" data-toggle="modal" data-target="#modalJustif"
                                data-id="{{ presence.id }}"
                                data-status="{{ status|escape }}"
                                data-justif="{{ path('get_excuse_proof_photo', {'id': presence.id}) }}"
                                {% if presence.excuseValidated is not null %}data-validate="{{ presence.excuseValidated == true ? '1' : '0' }}"{% endif %}
                                data-excuse="{{ presence.excuseDescription }}"
                                data-csrf="{{ csrf_token('validate' ~ presence.id) }}">Accéder au justificatif
                        </button>
                    {% endif %}
                </td>
            </tr>
        {% endif %}
    {% else %}
        <tr>
            <td colspan="5">Aucune absence / aucun retard</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<div class="modal fade" id="modalJustif" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Justificatif</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body text-center">
                <div>
                    <strong>Raison :</strong>
                    <span id="justifExcuse" class="mt-3"></span>
                </div>
                <div class="mt-2">
                    <strong>Etat actuel :</strong>
                    <span id="justifStatus" class="mt-3"></span>
                </div>
                <img src="" id="justifImage" class="mt-2">
            </div>
            <div class="modal-footer">
                <form method="post" action="{{ path('student_presence_validate', {'id': "ID"}) }}">
                    <input type="hidden" name="_method" value="POST">
                    <input type="hidden" name="_token" value="">
                    <button type="submit" value="validate" id="stateValidate" name="state" class="btn btn-success ml-4">
                        Valider
                    </button>
                    <button type="submit" value="refuse" id="stateRefuse" name="state" class="btn btn-danger ml-4">
                        Refuser
                    </button>
                </form>

            </div>
        </div>
    </div>
</div>

templates/student/form.html.twig
{% extends 'base.html.twig' %}

{% set title = update ? 'Modification de ' ~ student.username : "Ajout d'étudiant" %}
{% block title %}{{ parent() }} - {{ title }}{% endblock %}

{% block container %}
    <h1>{{ title }}</h1>

    {{ form_start(form, {'attr': {'class': 'd-inline'}}) }}
    {{ form_widget(form) }}
    <button class="btn btn-success" type="submit">Enregistrer</button>
    <a href="{{ path('student_index') }}" class="btn btn-secondary">Retour à la liste</a>
    {{ form_end(form) }}
    {% if update %}
        {% include 'ui/_delete_form.html.twig' with { id: student.id, path: 'student_delete' } %}
    {% endif %}
{% endblock %}

templates/student/import.html.twig
{% extends 'base.html.twig' %}

{% block title %}Import Students{% endblock %}

{% block container %}
    <h1>Importer des étudiants</h1>

    {{ form_start(import_form) }}
    {{ form_widget(import_form.file, {'attr': {'accept': mime_types}}) }}
    {{ form_rest(import_form) }}
    <button class="btn btn-success">{{ button_label|default('Import') }}</button>
    {# TODO Submit on file selected #}
    {{ form_end(import_form) }}

{% endblock %}

templates/student/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - Liste des étudiants{% endblock %}

{% block container %}
    <h3 class="m-bottom-10 m-top-10">Liste des étudiants</h3>

    <div class="pull-left">
        {{ knp_pagination_filter(pagination, {
            'class.name': 'Classe',
            'user.username': 'Numéro étudiant',
            'user.lastname': 'Nom',
            'user.firstname': 'Prénom',
        }, {'button': 'Rechercher'}) }}
    </div>

    <div class="pull-right">
        <a href="{{ path('student_new') }}" class="btn btn-success"><i class="fa fa-plus"></i> Nouveau</a>
        <a href="{{ path('student_import') }}" class="btn btn-primary"><i class="fa fa-upload"></i> Importer</a>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>{{ knp_pagination_sortable(pagination, 'Numéro étudiant', 'user.username') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'Nom', 'user.lastname') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'Prénom', 'user.firstname') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'Classe', 'class.name') }}</th>
                <th>Actions</th>

            </tr>
        </thead>
        <tbody>
        {% for user in pagination %}
            <tr>
                <td>{{ user.username }}</td>
                <td>{{ user.lastname }}</td>
                <td>{{ user.firstname }}</td>
                <td>{{ user.ClassGroup.name }}</td>
                <td>
                    <a class="btn btn-link btn-xs text-info" title="Voir le détail" data-toggle="tooltip"
                       href="{{ path('student_show', {'id': user.id}) }}"><i class="fa fa-eye"
                                                                             aria-hidden="true"></i></a>
                    <a class="btn btn-link btn-xs text-warning" title="Modifier ce compte" data-toggle="tooltip"
                       href="{{ path('student_edit', {'id': user.id}) }}"><i class="fa fa-edit" aria-hidden="true"></i></a>
                    {% include 'ui/_delete_form.html.twig' with { id: user.id, path: 'student_delete', min: true } %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">Aucun étudiant pour le moment.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="navigation">
        {{ knp_pagination_render(pagination, null, {}, {'align': 'center'}) }}
    </div>
{% endblock %}

templates/student/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - {{ student.firstname }} {{ student.lastname }}{% endblock %}

{% block container %}
    <h1>{{ student.firstname }} {{ student.lastname }}</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Numéro étudiant</th>
            <td>{{ student.username }}</td>
        </tr>
        <tr>
            <th>Nom</th>
            <td>{{ student.lastname }}</td>
        </tr>
        <tr>
            <th>Prénom</th>
            <td>{{ student.firstname }}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>{{ student.email }}</td>
        </tr>
        <tr>
            <th>Photo</th>
            <td><img src="{{ path('student_get_photo', {'id': student.id}) }}" height="100"></td>
        </tr>
        <tr>
            <th>Classe</th>
            <td>{{ student.ClassGroup.name }}</td>
        </tr>
        </tbody>
    </table>

    <a href="{{ path('student_index') }}" class="btn btn-secondary">Retour à la liste</a>

    <a href="{{ path('student_edit', {'id': student.id}) }}" class="btn btn-warning">Modifier</a>

    {{ include('ui/_delete_form.html.twig', { path: 'student_delete', id: student.id }) }}

    <h1 class="mt-3">Absences et retards de l'étudiant</h1>

    {% include 'student/absence.html.twig' with { 'presences': student.presences } %}

    <h1>Périphériques</h1>

    <table class="table">
        <tbody>
        {% for device in student.devices %}
            <tr>
                <td>{{ device }}</td>
                <td>
                    <form method="post" action="{{ path('delete_device', {'id': student.id, 'deviceId': device}) }}"
                          onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ?');"
                          class="d-inline">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ device) }}">
                        <button class="btn btn-danger ml-4"><i class="fa fa-trash"></i> Supprimer</button>
                    </form>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('proofModal') }}
{% endblock %}