src/Entity/EmailAlert.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EmailAlertRepository")
 */
class EmailAlert
{
    const PERIO_DAILY = 1;
    const PERIO_WEEKLY = 7;
    const PERIO_MONTHLY = 30;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="integer")
     * In days
     */
    private $periodicity;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $lastSent;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\ClassGroup")
     */
    private $watchedClasses;

    public function __construct()
    {
        $this->watchedClasses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPeriodicity(): ?int
    {
        return $this->periodicity;
    }

    public static function getLabelForPeriodicity(int $periodicity): string
    {
        switch ($periodicity) {
            case self::PERIO_DAILY:
                return 'Tous les jours';
            case self::PERIO_WEEKLY:
                return 'Chaque fin de semaine';
            case self::PERIO_MONTHLY:
                return 'Chaque fin de mois';
            default:
                return '';
        }
    }

    public function getPeriodicityLabel(): string
    {
        return self::getLabelForPeriodicity($this->periodicity);
    }

    public function setPeriodicity(int $periodicity): self
    {
        $this->periodicity = $periodicity;

        return $this;
    }

    public function getLastSent(): ?\DateTimeInterface
    {
        return $this->lastSent;
    }

    public function setLastSent(?\DateTimeInterface $lastSent): self
    {
        $this->lastSent = $lastSent;

        return $this;
    }

    /**
     * @return Collection|ClassGroup[]
     */
    public function getWatchedClasses(): Collection
    {
        return $this->watchedClasses;
    }

    public function addWatchedClass(ClassGroup $watchedClass): self
    {
        if (!$this->watchedClasses->contains($watchedClass)) {
            $this->watchedClasses[] = $watchedClass;
        }

        return $this;
    }

    public function removeWatchedClass(ClassGroup $watchedClass): self
    {
        if ($this->watchedClasses->contains($watchedClass)) {
            $this->watchedClasses->removeElement($watchedClass);
        }

        return $this;
    }
}

src/Form/EmailAlertType.php
<?php

namespace App\Form;

use App\Entity\ClassGroup;
use App\Entity\EmailAlert;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EmailAlertType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email', EmailType::class, [])
            ->add('periodicity', ChoiceType::class, [
                'label' => 'Périodicité',
                'choices' => [
                    EmailAlert::getLabelForPeriodicity(EmailAlert::PERIO_DAILY) => EmailAlert::PERIO_DAILY,
                    EmailAlert::getLabelForPeriodicity(EmailAlert::PERIO_WEEKLY) => EmailAlert::PERIO_WEEKLY,
                    EmailAlert::getLabelForPeriodicity(EmailAlert::PERIO_MONTHLY) => EmailAlert::PERIO_MONTHLY,
                ]
            ])
            ->add('watchedClasses', EntityType::class, [
                'label' => 'Classes',
                'class' => ClassGroup::class,
                'choice_label' => 'name',
                'multiple' => true,
                'attr' => ['class' => 'select2'],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => EmailAlert::class,
        ]);
    }
}

src/Controller/EmailAlertController.php
<?php

namespace App\Controller;

use App\Entity\EmailAlert;
use App\Form\EmailAlertType;
use App\Repository\EmailAlertRepository;
use App\Security\CheckAccessRights;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/alert")
 */
class EmailAlertController extends AbstractController
{
    /**
     * @Route("/", name="email_alert_index", methods={"GET"})
     * @throws \App\Exception\UserException
     */
    public function index(Request $request, PaginatorInterface $paginator, EmailAlertRepository $repository): Response
    {
        CheckAccessRights::hasAdminOrSuperAdminRole($this->getUser());

        $query = $repository->getFindAllQuery();

        $pagination = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            10
        );

        return $this->render('email_alert/index.html.twig', [
            'pagination' => $pagination
        ]);
    }

    /**
     * @Route("/new", name="email_alert_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $alert = new EmailAlert();
        $form = $this->createForm(EmailAlertType::class, $alert);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            $entityManager->persist($alert);
            $entityManager->flush();

            return $this->redirectToRoute('email_alert_index');
        }

        return $this->render('email_alert/form.html.twig', [
            'alert' => $alert,
            'form' => $form->createView(),
            'update' => false,
        ]);
    }

    /**
     * @Route("/{id}", name="email_alert_show", methods={"GET"})
     */
    public function show(EmailAlert $alert): Response
    {
        return $this->render('email_alert/show.html.twig', [
            'alert' => $alert,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="email_alert_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, EmailAlert $alert): Response
    {
        $form = $this->createForm(EmailAlertType::class, $alert);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('email_alert_index', [
                'id' => $alert->getId(),
            ]);
        }

        return $this->render('email_alert/form.html.twig', [
            'alert' => $alert,
            'form' => $form->createView(),
            'update' => true,
        ]);
    }

    /**
     * @Route("/{id}", name="email_alert_delete", methods={"DELETE"})
     */
    public function delete(Request $request, EmailAlert $alert): Response
    {
        if ($this->isCsrfTokenValid('delete' . $alert->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($alert);
            $entityManager->flush();
        }

        return $this->redirectToRoute('email_alert_index');
    }
}

templates/email_alert/form.html.twig
{% extends 'base.html.twig' %}

{% set title = update ? 'Modification de ' ~ alert.email : "Ajout d'alerte email" %}
{% block title %}{{ parent() }} - {{ title }}{% endblock %}

{% block container %}
    <h1>{{ title }}</h1>

    {{ form_start(form, {'attr': {'class': 'd-inline'}}) }}
    {{ form_widget(form) }}
    <button class="btn btn-success" type="submit">Enregistrer</button>
    <a href="{{ path('email_alert_index') }}" class="btn btn-secondary">Retour à la liste</a>
    {{ form_end(form) }}
    {% if update %}
        {% include 'ui/_delete_form.html.twig' with { id: alert.id, path: 'email_alert_delete' } %}
    {% endif %}
{% endblock %}

templates/email_alert/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - Liste des alertes programmées{% endblock %}

{% block container %}
    <h3>Liste des alertes programmées</h3>
    <div class="pull-left">
        {{ knp_pagination_filter(pagination, {
            'alert.email': 'Email',
            'alert.periodicity': 'Périodicité',
        }, {'button': 'Rechercher'}) }}
    </div>

    <div class="pull-right">
        <a href="{{ path('email_alert_new') }}" class="btn btn-success"><i class="fa fa-plus"></i> Nouvelle"</a>
    </div>


    <table class="table">
        <thead>
        <tr>
            <th>{{ knp_pagination_sortable(pagination, 'Email', 'alert.email') }}</th>
            <th>{{ knp_pagination_sortable(pagination, 'Periodicité', 'alert.periodicity') }}</th>
            <th>Actions</th>

        </tr>
        </thead>
        <tbody>
        {% for alert in pagination %}
            <tr>
                <td>{{ alert.email }}</td>
                <td>{{ alert.periodicityLabel }}</td>
                <td>
                    <a class="btn btn-link btn-xs text-info" title="Voir le détail" data-toggle="tooltip"
                       href="{{ path('email_alert_show', {'id': alert.id}) }}"><i class="fa fa-eye"
                                                                                  aria-hidden="true"></i></a>
                    <a class="btn btn-link btn-xs text-warning" title="Modifier cette alerte" data-toggle="tooltip"
                       href="{{ path('email_alert_edit', {'id': alert.id}) }}"><i class="fa fa-edit"
                                                                                  aria-hidden="true"></i></a>
                    {% include 'ui/_delete_form.html.twig' with { id: alert.id, path: 'email_alert_delete', min: true } %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">Aucune alerte pour le moment.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="navigation">
        {{ knp_pagination_render(pagination, null, {}, {'align': 'center'}) }}
    </div>
{% endblock %}

templates/email_alert/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - Alerte pour {{ alert.email }}{% endblock %}

{% block container %}
    <h1>Alerte pour {{ alert.email }}</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Email</th>
            <td>{{ alert.email }}</td>
        </tr>
        <tr>
            <th>Periodicité</th>
            <td>{{ alert.periodicityLabel }}</td>
        </tr>
        <tr>
            <th>Dernier envoi</th>
            <td>{{ alert.lastSent|date('d/m/Y à H:i') }}</td>
        </tr>
        </tbody>
    </table>

    <h1>Classes</h1>

    <table class="table">
        <tbody>
        {% for classGroup in alert.watchedClasses %}
            <tr>
                <td>{{ classGroup.name }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('email_alert_index') }}" class="btn btn-secondary">Retour à la liste</a>

    <a href="{{ path('email_alert_edit', {'id': alert.id}) }}" class="btn btn-warning">Modifier</a>

    {% include 'ui/_delete_form.html.twig' with { id: alert.id, path: 'email_alert_delete' } %}
{% endblock %}